### PR TITLE
Add centroid and FWZI

### LINKED ISSUE #38: extract() does not work
`Data` class  has neither `set_x()` nor `set_y()` implemented.

```python
>>> data
Data([ 0.09934656, -0.02764913,  0.12954146, ...,  0.07568395,  0.34271905, -0.32397091])
>>> extract(data, (10000, 20000))
.../Pyfocal-0.1a1-py2.7.egg/pyfocal/analysis/statistics.pyc in extract(data, x_range)
     25 
     26     result = Data(x[slice])
---> 27     result.set_x(x[slice], unit=spectrum_data.x.unit)
     28     result.set_y(y[slice], unit=spectrum_data.y.unit)
     29 

AttributeError: 'Data' object has no attribute 'set_x'
```

### PR DESCRIPTION
**Pull request by pllim**
Added centroid and FWZI function (see #20). Someone need to check to make sure they are doing the correct math. I am just guessing at some part. Also fixed the statistics functions that did not work.

General clean up of statistics module. Also added API doc for statistics module. Added example on how to use `Data` class.

Fixes #38.

### CODE REVIEW

**Comment by pllim** [comment]
Merge now, test later? Or test first, then merge?

c/c @nmearl , @hcferguson

**Comment by nmearl** [comment]
Looks great. I guess this a good time to have a conversation about branches in the repo. Would it be preferred to continue on merging to master, and point everyone else to the tag v0.1rc1 release for the 'frozen' usage, or should we start a new "develop" branch, and use that as our sprint branch to merge to master at the end?

**Comment by pllim** [comment]
Well... @ibusko has been committing directly to master...

I'm not a release guru. Will have to ask @stscieisenhamer or @perrygreenfield.

**Comment by nmearl** [comment]
Ah, crap. I didn't even notice he was pushing into master.

**Comment by ibusko** [comment]
Is there any other branch? I see only master in github.

**Comment by pllim** [comment]
From the sprint, it was decided that we just merge to master for development, and tag separately for release. So, I'm merging this.

**Pull request merged**
