### PR TITLE
Make pyfocal able to run in Anaconda Python 2.7

### LINKED ISSUE #24: ImportError qtpy.QtWidgets
Under Anaconda, I am unable to start `pyfocal`. Am I missing some dependency? `qtpy` is nothing I have heard of before.

```python
Traceback (most recent call last):
  File ".../bin/pyfocal", line 9, in <module>
    load_entry_point('pyfocal==0.1a1', 'console_scripts', 'pyfocal')()
  File ".../lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 547, in load_entry_point
  File ".../lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 2719, in load_entry_point
  File ".../lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 2379, in load
  File ".../lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 2385, in resolve
  File ".../site-packages/pyfocal-0.1a1-py2.7.egg/pyfocal/app.py", line 7, in <module>
    from qtpy.QtWidgets import *
ImportError: No module named qtpy.QtWidgets
```

### PR DESCRIPTION
**Pull request by pllim**
This might be a bit contraversial, but it enables `pyfocal` to be run from Anaconda in Python 2. Effectively fixes #24 and #28. 

Here is what I see without using Homebrew etc.

screenshot

### CODE REVIEW

**Comment by pllim** [comment]
@nmearl , what do you think? I understand if you want to freeze your current master and hold this off. We can also create a tag for the version freeze and merge this into master. Up to you.

c/c @ibusko , @stscieisenhamer

**Comment by nmearl** [comment]
This looks good. One thing to note is that any file in the `ui/qt` directory will be overwritten when they are generated again, so I would strongly suggest not editing this files. I realize this conflicts because they natively import PyQt5 right now.

The solution is to extend the bash file in `ui/qt/uic/gen_uic.sh` to edit the python files after generation to replace those lines with calls to `qtpy`.

**Comment by pllim** [comment]
Re: uic

That is why I asked about versioning them in #29. Why not just have `pyfocal` generate it upon install if it depends on what user has? Or pre-generate them for all supported Qt4/Qt5/PySide and then choose during runtime?

**Comment by nmearl** [comment]
Generating the python files requires the user to have those qt tools installed on their system, which will most likely not be the case.

Pre-generation is probably the best bet, and the one I was initially aiming for (essentially an expansion of how it currently is implemented).

**Comment by pllim** [comment]
Anyways, I think we should handle the `uic` stuff as a separate issue. Please test this PR and make sure I didn't break anything on your side. And merge however you want it, if you wish.

**Comment by nmearl** [comment]
:+1: Locally. I'm going to merge this now, and we'll use this as the "frozen" distribution.

**Comment by pllim** [comment]
Thanks!

**Pull request merged**
